"""empty message

Revision ID: 792dece152e9
Revises: 
Create Date: 2018-08-31 12:12:15.336781

"""
from alembic import op
from sqlalchemy import Column, ForeignKey
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '792dece152e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('date_submitted', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignment_date_submitted'), 'assignment', ['date_submitted'], unique=False)
    op.create_index(op.f('ix_assignment_due_date'), 'assignment', ['due_date'], unique=False)
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('weeks', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instructor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('semester',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('days_missed', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('f_name', sa.String(), nullable=True),
    sa.Column('l_name', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.add_column('assignment',
        Column('student_id', sa.Integer(), ForeignKey('student.id'))
    )
    op.add_column('course',
        Column('instructor_id', sa.Integer(), ForeignKey('instructor.id'))
    )
    op.add_column('course',
        Column('semester_id', sa.Integer(), ForeignKey('semester.id'))
    )
    op.add_column('instructor',
        Column('course_id', sa.Integer(), ForeignKey('course.id'))
    )
    op.add_column('student',
        Column('course_id', sa.Integer(), ForeignKey('course.id'))
    )
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('student')
    op.drop_table('semester')
    op.drop_table('role')
    op.drop_table('instructor')
    op.drop_table('course')
    op.drop_index(op.f('ix_assignment_due_date'), table_name='assignment')
    op.drop_index(op.f('ix_assignment_date_submitted'), table_name='assignment')
    op.drop_table('assignment')
    # ### end Alembic commands ###