"""empty message

Revision ID: eb1d19907602
Revises: fdb3e0d1f7b4
Create Date: 2018-08-28 19:46:28.603638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb1d19907602'
down_revision = 'fdb3e0d1f7b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('instructor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'course', 'instructor', ['instructor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.drop_column('course', 'instructor_id')
    # ### end Alembic commands ###
