"""empty message

Revision ID: efcdc2d7d944
Revises: 
Create Date: 2018-09-28 13:25:21.193112

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Column, ForeignKey


# revision identifiers, used by Alembic.
revision = 'efcdc2d7d944'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('date_submitted', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignment_date_submitted'), 'assignment', ['date_submitted'], unique=False)
    op.create_index(op.f('ix_assignment_due_date'), 'assignment', ['due_date'], unique=False)
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('weeks', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instructor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('f_name', sa.String(), nullable=True),
    sa.Column('l_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('in_class', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('semester',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('f_name', sa.String(), nullable=True),
    sa.Column('l_name', sa.String(), nullable=True),
    sa.Column('days_missed', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('f_name', sa.String(), nullable=True),
    sa.Column('l_name', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    op.add_column('assignment',
        Column('student_id', sa.Integer(), ForeignKey('student.id'))
    )

    op.add_column('course',
        Column('semester_id', sa.Integer(), ForeignKey('semester.id'))
    )

    op.add_column('course',
        Column('instructor_id', sa.Integer(), ForeignKey('instructor.id'))
    )

    op.add_column('instructor',
        Column('course_id', sa.Integer(), ForeignKey('course.id'))
    )

    op.add_column('instructor',
        Column('user_id', sa.Integer(), ForeignKey('user.id'))
    )

    op.add_column('note',
        Column('course_id', sa.Integer(), ForeignKey('course.id'))
    )

    op.add_column('note',
        Column('instructor_id', sa.Integer(), ForeignKey('instructor.id'))
    )

    op.add_column('student',
        Column('course_id', sa.Integer(), ForeignKey('course.id'))
    )

    op.add_column('student',
        Column('user_id', sa.Integer(), ForeignKey('user.id'))
    )
    
    op.add_column('user',
        Column('role_id', sa.Integer(), ForeignKey('role.id'))
    )

    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('student')
    op.drop_table('semester')
    op.drop_table('role')
    op.drop_table('note')
    op.drop_table('instructor')
    op.drop_table('course')
    op.drop_index(op.f('ix_assignment_due_date'), table_name='assignment')
    op.drop_index(op.f('ix_assignment_date_submitted'), table_name='assignment')
    op.drop_table('assignment')
    # ### end Alembic commands ###
